name: yarn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node packages
      id: packages-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      if: steps.packages-cache.outputs.cache-hit != 'true'
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Run test suite
      id: test
      run: ./node_modules/.bin/jest

    - name: Codecov
      uses: codecov/codecov-action@v1.0.15
